import type { Metadata } from "next";
import { Geist, Geist_Mono, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import HeaderComponent from "../src/components/HeaderComponent/HeaderComponent";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const jakartaSans = Plus_Jakarta_Sans({
  subsets:["latin"],
  variable: "--font-jakarta-sans"
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "EMCUS - Software Development for Fire & Safety",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${jakartaSans.variable} ${jakartaSans.variable} antialiased xl:max-w-7xl xl:mx-auto xl:px-4 px-0`}
      >
        {children}
      </body>
    </html>
  );
}
